### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AirQuick** [fukuchiharuki/talk.css#1]
Neat. 👍 
Can you specify the license type or provide some licensing terms? Thanks.

**Comment by fukuchiharuki** [comment]
MITにしました。
cssファイルにライセンス表示を入れておきました。
ので、そのまま使ってもらえると思います。

I made it licensed under the MIT License, and
I wrote license information on the file talk.css .
You can use it without constraint, right?

**Comment by AirQuick** [comment]
Thanks for the clarification and also for selecting the MIT which is easy to handle.
Keep up with the good work!
